version: "3.8"

services:
  auth-container:
    build: ./auth
    ports:
      - "3000:3000"
    networks:
      - minha-rede
    depends_on:
      - rabbitmq

  product-container:
    build: ./product
    ports:
      - "3001:3001"
    networks:
      - minha-rede
    depends_on:
      - rabbitmq

  order-container:
    build: ./order
    ports:
      - "3002:3002"
    networks:
      - minha-rede
    depends_on:
      - rabbitmq

  payment-container:
    build: ./payment
    ports:
      - "3003:3003"
    networks:
      - minha-rede
    depends_on:
      - rabbitmq

  notification-container:
    build: ./notification
    ports:
      - "3004:3004"
    networks:
      - minha-rede
    depends_on:
      - rabbitmq
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - minha-rede

networks:
  minha-rede:
    driver: bridge
